name: build images

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "*" ]

permissions:
  contents: read
  packages: write

jobs:
  php-apps:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    name: build base image for APPS
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        name: login to ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./php/apps
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/php:apps